<?php

class LocalSettingsGenerator {

	public $settings;

	public function __construct( $settings = array() ) {
		$this->settings = $settings;
	}

	public function setSettings( $settings ) {
		$this->settings = $settings;
	}

	public function addSettings( $settings ) {
		$this->settings = array_merge( $this->settings, $settings );
	}

	public function getContent() {
		$content = $this->getHeader() . PHP_EOL;
		foreach ( $this->settings as $conf ) {
			if ( $conf->isDefault() ) {
				// Ignore default values, they are set in DefaultSettings.php
				continue;
			}
			$code = var_export( $conf->getNewValue(), true );
			$content .= "\${$conf->getName()} = $code;\n";
		}
		return $content;
	}

	public function getHeader() {
		return <<<EOS
<?php
// This file has been automatically generated by LocalSettingsGenerator.php
// Do NOT EDIT this block
if ( !defined( 'ENTRY_POINT' ) ) {
    die( 'This is not an entry point. LocalSettings' );
}
// You can edit settings from here
EOS;
	}

	public function writeFile( $file ) {
		$text = $this->getContent();
		$result = file_put_contents( $file, $text );
		return $result !== false;
	}
}